In [ ]:
#numpy
#numpy is an open source library that is use to handle scientific calculations

#diff b/w list and numpy:
#(1) list hetrogeneous data type and numpy is hemogeneous data type
#(2) list takes more memory as compare to numpy( data in contiguous memory blocks)
#(3) numpy is faster as compare to list ( Python lists which are collections of pointers to objects)

In [ ]:
# NumPy (also called Numerical Python) is a highly flexible, optimized, open-source library meant for array processing.
#  It is use to handle scientific calculations  and also provides tools for delivering high-end performance while dealing with N-dimensional array objects  .

In [ ]:
#pip install numpy --------> for vs code
#!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1,23,45,67,"paridhi"]
type(a)

list

In [ ]:
b = np.array(a)
b

array(['1', '23', '45', '67', 'paridhi'], dtype='<U21')

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#user define array
a = []
size = int(input("enter size : "))
for i in range(size):
  val = int(input("enter number :"))
  a.append(val)
print(a)
b = np.array(a)
b

enter size : 3
enter number :23
enter number :12
enter number :45
[23, 12, 45]


array([23, 12, 45])

In [ ]:
# matrix ----> matrix is a two-dimensional data structure where numbers are arranged into rows and columns.
a = [[1,2,3],[4,5,6],[7,8,9]]
a
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#matrix
#row1 = [1,2,3]
#row2 = [4,5,6]
#row3 = [7,8,9]


#col1= [1,4,7]
#col2 = [2,5,8]
#col3 = [3,6,9]

# total num of elements = rows * col

In [ ]:
print("total rows and columns :" , b.shape)
print("total num of element :" , b.size)


total rows and columns : (3, 3)
total num of element : 9


In [ ]:
a = [[1,2,3,56],[4,5,6,78],[7,8,9,90]]
a
b = np.array(a)
b

array([[ 1,  2,  3, 56],
       [ 4,  5,  6, 78],
       [ 7,  8,  9, 90]])

In [ ]:
print("total rows and columns :" , b.shape)
print("total num of element :" , b.size)


total rows and columns : (3, 4)
total num of element : 12


In [ ]:
# how to check dimensions
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a.ndim

2

In [ ]:
a = np.array([[[1,2,3,4],[5,6,7,8]]])
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [ ]:
a.ndim

3

In [ ]:
#images --> pixels(0-255) ---> normalize(0-1) ---> matrix ----->operations
# DL ---> artificial neurons ---> weight ---> randomly creations ----> numpy
# datasets ---> dummy entry --> ramdom module ----> attach pandas


# **Pre define functions**

In [ ]:
# (1) zeros() ---> will create an array in which all the values will be zero either in 1-D or 2-D(multi dimensional)


In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#(2) ones---> will create an array in which all the values will be one either in 1-D or 2-D(multi dimensional)

In [ ]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np

In [ ]:
# (3) eye() ----> it will create an array in which diagonal positional element will be
# 1 and rest all are 0

In [ ]:
a = np.eye(3)     #rows = column ----> symmetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3,4)      ### row != columns ----->asymmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#(4) diag() ---> it will create an array in which we can set our custom values at digonal position

In [ ]:
a = np.diag([12,24,25,29,5])
a

array([[12,  0,  0,  0,  0],
       [ 0, 24,  0,  0,  0],
       [ 0,  0, 25,  0,  0],
       [ 0,  0,  0, 29,  0],
       [ 0,  0,  0,  0,  5]])

In [ ]:
# (5) random module ---->
# (a) Randint()  -----> it will create an array of random numbers in a given range
# synrax : np.random.randint(min_range ,max_range,total_numbers)

In [ ]:
a = np.random.randint(1,10,3)
a

array([1, 2, 5])

In [ ]:
# (b) rand()----> it will generate random numbers from 0-1
# syntax : np.random.rand(total_numbers)

In [ ]:
a = np.random.rand(4)
a

array([0.47869636, 0.94534692, 0.43895157, 0.5216618 ])

In [ ]:
# (c)
#exmaple
#dataset(emp_data,emp_salary,domain) ----> randomly column add(working_hours)

In [ ]:
# (c) seed()---> it will fix or lock our generated data
# syntax :
# np.random.seed(random_num)
# a = np.random.randint(1,10,2)

In [ ]:
np.random.seed(3)
a = np.random.randint(1,10,2)
a

array([9, 4])

In [ ]:
#view ---> it make direct changes to the original array  Vs
# copy ---> it create a copy of the array and apply changes to it and doesn't effect the original array

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b = a[1:4]
b[:] = 0
b

array([0, 0, 0])

In [ ]:
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [ ]:
# copy

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[1:4].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

#reshaping in array
#total rows * columns = total elements

In [ ]:
a= np.random.randint(1,50,12)
a

array([30, 35, 26,  1, 20,  9,  5, 41, 10, 39, 21, 43])

In [ ]:
# 1*12 ,12 *1
# 2*6 , 6*2
# 3*4 , 4*3

In [ ]:
a.reshape(2,6)

array([[30, 35, 26,  1, 20,  9],
       [ 5, 41, 10, 39, 21, 43]])

In [ ]:
a.reshape(3,4)

array([[30, 35, 26,  1],
       [20,  9,  5, 41],
       [10, 39, 21, 43]])

In [ ]:
# y = mx + b
# m = matrix ----> weights
# x = values ---> matrix
# matrix(column) * matrixm(row)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(-1,3)

array([[24, 21, 30],
       [43,  3, 17],
       [ 1, 23, 24],
       [ 1, 21, 28]])

In [ ]:
a.reshape(6,-1)

array([[30, 35],
       [26,  1],
       [20,  9],
       [ 5, 41],
       [10, 39],
       [21, 43]])

# operations on array

In [ ]:
 a = np.arange(1,5,2)
 a

array([1, 3])

In [ ]:
 a = np.arange(1,5)
 a

array([1, 2, 3, 4])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
a+b

array([ 6,  8, 10, 12])

In [ ]:
a-b

array([-4, -4, -4, -4])

In [ ]:
a= np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b= np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b)    ## multiplication on array

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a >10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [ ]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [ ]:
a**3

array([ 1,  8, 27])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
np.sum(a, axis = 1)   # axis = 1 ----> row wise operation


array([ 6, 15, 24])

In [ ]:
np.sum(a, axis = 0)      # axis = 0 ----> column wise operation

array([12, 15, 18])

In [ ]:
import numpy as np

In [ ]:
# unique() ---> it will create an array in which it will remove duplicate values and return 3 arrays:
# arr ---> unique elements of array
# return_index = True ---> indexes of the unique elements
# return_counts = True ----> frequency of each unique element

In [ ]:
a = np.array([1,1,2,3,4,1,4,5,4,7,4,2])
a

array([1, 1, 2, 3, 4, 1, 4, 5, 4, 7, 4, 2])

In [ ]:
b = np.unique (a, return_index = True , return_counts = True)
b

(array([1, 2, 3, 4, 5, 7]),
 array([0, 2, 3, 4, 7, 9]),
 array([3, 2, 1, 4, 1, 1]))

In [ ]:
#linspace()----> it will return an array in which elements with a same gap in specific  range .
# syntax : np.linspace(min_num , max_num , total_numbers)

In [ ]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# horizontal and vertical stacking ---->
# horizontal stacking ---> it will add 2 or more arrays horizontally

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
c = np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# vertical stacking ---> it will add 2 or more arrays vertically

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
import numpy as np
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a = np.random.randint(10,50,5)
print(a.shape)
print(a.size)
print(type(a))

(5,)
5
<class 'numpy.ndarray'>


In [ ]:
a = np.arange(0,6).reshape(-1,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.ndim

2

In [ ]:
b = np.array([10,20,30,40,50,60])
print(b[1])
print(b[2:5])
print(b[0: :2])

20
[30 40 50]
[10 30 50]


In [ ]:
b = np.array([10,20,30,40,50,60]).reshape(2,3)
print(b)
print(b[0,0:])


[[10 20 30]
 [40 50 60]]
[10 20 30]
